services:
  redis-stack:
    image: redis/redis-stack-server:latest # for production
    # image: redis/redis-stack:latest # for development
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    command: redis-server --requirepass mysecretpassword
    environment:
      - REDIS_PASSWORD=mysecretpassword
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
    driver: local
